channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
#  - python=3.10
#  - pip=21.0
#  - matplotlib=3.3
  - occt=7.7.0
  - cadquery
  - pip:
    - shapely
#    - jupyter-cadquery==2.2.0
#    - cadquery-massembly~=0.9
#    - orbitcontrol-patch~=0.1.0
#    - cython
#    - cython-csg
#    - pythreejs
#    - petrify
    - descartes
    - numpy

