name: k3d
channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python>=3.8
  - pip=21.0
  - cadquery=2.1
  - matplotlib=3.3
  - notebook>5.2
  - jupyterlab>1.1
  - ipywidgets
  - pandas
  - scipy
  - numba
  - scikit-image
  - vtk
  - pip:
     - k3d
     - nibabel
     - shapely
     - solidpython
     - jupyter-cadquery==2.2.0
     - cadquery-massembly~=0.9
     - orbitcontrol-patch~=0.1.0
