#!/bin/bash
cd /tmp
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter serverextension enable --py jupyterlab_git
jupyter nbextension enable --py --sys-prefix k3d
jupyter labextension install k3d
jupyter nbextension install --py --sys-prefix k3d

apt-get install -y libqscintilla2-qt5-dev

